dist: xenial
sudo: required
language: cpp
compiler: gcc

arch:
    - AMD64
    - ppc64le

addons:
  apt:
    packages:
    - curl
    - libcurl4-gnutls-dev
    - ca-certificates
    - software-properties-common
    - python-software-properties
    - gnupg-curl

env:
  - PG_VERSION=9.6 GDAL_VERSION=1.11
  - PG_VERSION=9.6 GDAL_VERSION=2.2.4
  - PG_VERSION=10 GDAL_VERSION=2.3.3
  - PG_VERSION=11 GDAL_VERSION=2.4.4
  - PG_VERSION=12 GDAL_VERSION=2.4.4

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql-9.1
  - sudo apt-get -y --purge remove postgresql-9.2
  - sudo apt-get -y --purge remove postgresql-9.3
  - sudo apt-get -y --purge remove postgresql-9.4
  - sudo apt-get -y --purge remove postgresql-9.5
  - sudo apt-get -y --purge remove postgresql-9.6
  - sudo apt-get -y --purge remove postgresql-10
  - sudo apt-get -y --purge remove postgresql-11
  - sudo apt-get -y --purge remove postgresql-common
  - sudo apt-get -y autoremove
  - sudo rm -rf /var/lib/postgresql
  - apt-key adv --fetch-keys https://www.postgresql.org/media/keys/ACCC4CF8.asc
  - sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main $PG_VERSION"
  - sudo apt-get update -qq
  - sudo apt-get -y install postgresql-$PG_VERSION postgresql-server-dev-$PG_VERSION
  - sudo cp ci/pg_hba.conf /etc/postgresql/$PG_VERSION/main/pg_hba.conf
  - sudo /etc/init.d/postgresql reload

  - if [[ $GDAL_VERSION == 1* ]]; then sudo apt-get install libgdal1i libgdal-dev; fi
  - if [[ $GDAL_VERSION == 2* ]]; then bash ci/gdal_build.sh $GDAL_VERSION; fi
  - if [[ $GDAL_VERSION == 3* ]]; then bash ci/gdal_build.sh $GDAL_VERSION; fi
  # needs proj6


script:
  - make && sudo make install && sudo chmod 755 $HOME && (PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false))


